export const STATES_AND_CITIES = {
    'Andhra Pradesh': [],
    'Arunachal Pradesh': [],
    'Assam': [],
    'Bihar': [],
    'Chhattisgarh': [],
    'Goa': [],
    'Gujarat': [],
    'Haryana': [
        'Ambala',
        'Bhiwani',
        'Charkhi Dadri',
        'Faridabad',
        'Fatehabad',
        'Gurugram',
        'Hisar',
        'Jhajjar',
        'Jind',
        'Kaithal',
        'Karnal',
        'Kurukshetra',
        'Mahendragarh',
        'Nuh',
        'Palwal',
        'Panchkula',
        'Panipat',
        'Rewari',
        'Rohtak',
        'Sirsa',
        'Sonipat',
        'Yamunanagar'
    ],
    'Himachal Pradesh': [],
    'Jharkhand': [],
    'Karnataka': [],
    'Kerala': [],
    'Madhya Pradesh': [],
    'Maharashtra': [
        'Ahmednagar',
        'Akola',
        'Amravati',
        'Aurangabad',
        'Beed',
        'Bhandara',
        'Buldhana',
        'Chandrapur',
        'Dhule',
        'Gadchiroli',
        'Gondia',
        'Hingoli',
        'Jalgaon',
        'Jalna',
        'Kolhapur',
        'Latur',
        'Mumbai City',
        'Mumbai Suburban',
        'Nagpur',
        'Nanded',
        'Nandurbar',
        'Nashik',
        'Osmanabad',
        'Palghar',
        'Parbhani',
        'Pune',
        'Raigad',
        'Ratnagiri',
        'Sangli',
        'Satara',
        'Sindhudurg',
        'Solapur',
        'Thane',
        'Wardha',
        'Washim',
        'Yavatmal'
    ],
    'Manipur': [],
    'Meghalaya': [],
    'Mizoram': [],
    'Nagaland': [],
    'Odisha': [],
    'Punjab': [],
    'Rajasthan': [],
    'Sikkim': [],
    'Tamil Nadu': [],
    'Telangana': [],
    'Tripura': [],
    'Uttar Pradesh': [],
    'Uttarakhand': [],
    'West Bengal': [],
    'Andaman and Nicobar Islands': [],
    'Chandigarh': [],
    'Dadra and Nagar Haveli and Daman and Diu': [],
    'Delhi': [
        'New Delhi',
        'North Delhi',
        'South Delhi',
        'East Delhi',
        'West Delhi',
        'Central Delhi',
        'North West Delhi',
        'South West Delhi',
        'South East Delhi',
        'Shahdara'
    ],
    'Jammu and Kashmir': [],
    'Ladakh': [],
    'Lakshadweep': [],
    'Puducherry': []
};

export const LANGUAGES = [
    { label: 'English', value: 'English' },
    { label: 'Hindi', value: 'Hindi' },
    { label: 'Marathi', value: 'Marathi' }
];

export const API_BASE_URL = 'http://localhost:8000';
